/**
 * 路由表管理
 */
export class RoutePath {
  static readonly SplashPage = "pages/SplashPage"
  static readonly MainPage = "pages/MainPage"
  static readonly CategoryPage = "pages/CategoryPage"
  static readonly ContainerPage = "pages/container/ContainerPage"
  static readonly TopicDetailPage = "pages/topicDetail/TopicDetailPage"
  static readonly DetailPage = "pages/commonDetail/DetailPage"
  static readonly CategoryDetailPage = "pages/categoryDetail/CategoryDetailPage"
  static readonly TestPage = "pages/test/TestPage"
  static readonly TestHorizontalPage = "pages/test/TestHorizontalPage"
  static readonly TestHorizontalPage2 = "pages/test/TestHorizontalPage2"
  static readonly CoordinatePage = "pages/hot/CoordinatePage"
}